FROM nginx

RUN rm /etc/nginx/conf.d/default.conf

COPY /etc/cert /etc/cert
COPY ./default.conf /etc/nginx/conf.d/default.conf
COPY ./nginx.conf /etc/nginx/nginx.conf

CMD [ "nginx", "-g", "daemon off;" ]

EXPOSE 80 443